SAVE_ROOT: '../experiments/adam/epochs_100/'
SYSTEM:
  DEVICE: 'cuda:0'
  EXP_NAME: 'RFCM_2_classes_gamma_0_5_equalize_adam'
SOLVER:
  BATCH_SIZE: 5
  ITER_SIZE: 4
  IMG_SIZE: (425, 425)
  EPOCHS: 100
  OPTIMIZER: 'Adam'
  LOSS: 'RFCM'
  LR: 5e-4
  USE_POLY_DECAY: false
  FUZZY_FACTOR: 2
  REGULARIZER: 0.0016
MODEL:
  CLASSES: 2
  TIME_STEPS: 3
DATA:
  TRAIN:
    ROOT: '../datasets/JSRT_dataset/pre_processed_2048_2048/'
    LIST: '../datasets/JSRT_dataset/train_no_labels.lst'
  TEST:
    ROOT: '../datasets/JSRT_dataset/pre_processed_2048_2048/'
    LIST: '../datasets/JSRT_dataset/test.lst'
    GT_ROOT: '../datasets/JSRT_dataset/masks/lungs/'
